import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useState, useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [temp, setTemp] = useState(20);
  const [isCelcius, setIsCelcius] = useState(true);
  const [address, setAddress] = useState("a place near you");

  // Fetch the weather only once
  useEffect(()=>{
    fetchWeather();
  },[]);

  // API call to another website, which takes some time to return a result
  async function fetchWeather() {
    const response = await fetch("https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/melbourne?unitGroup=metric&key=F34RGXAKG75EX69MUH7E6W7WQ&contentType=json", {
      "method": "GET",
      "headers": {
      }
      })
    // Here the weather data gets returned
    const weather = await response.json();
    setTemp(weather.currentConditions.temp);
    setAddress(weather.address);
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            The temperature is:&nbsp;
            <code className={styles.code}>{isCelcius ? temp : Math.floor((temp*9/5) + 32)}</code> &nbsp;
             {isCelcius ? "celcius" : "fahrenheit"} in&nbsp;
            <code className={styles.code}>{address}</code>
          </p>
          <button onClick={()=>{setIsCelcius(!isCelcius)}}>Hello</button>
          </div></main> 
    </>
  )
}